# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shiftswapper_development
  pool: 5
  username: localhost
  password: admin
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shiftswapper_test
  pool: 5
  username: localhost
  password: admin

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shiftswapper_production
  pool: 5
  username: shiftswapper
  password: admin
